"""The real names of the companies the fake broker lists (fake_kite), so the demo world shows "HDFC Bank" rather than
"Hdfcbank" and can be searched by name the way the real list can. Names as the companies are called, without
"Limited"."""

NAMES = {
    "AARTIIND": "Aarti Industries", "ABBOTINDIA": "Abbott India", "ADANIENT": "Adani Enterprises",
    "ADANIGREEN": "Adani Green Energy", "ADANIPORTS": "Adani Ports and Special Economic Zone", "ADANIPOWER": "Adani Power",
    "ALKEM": "Alkem Laboratories", "AMBER": "Amber Enterprises India", "AMBUJACEM": "Ambuja Cements", "ANANTRAJ": "Anant Raj",
    "ANGELONE": "Angel One", "APLAPOLLO": "APL Apollo Tubes", "APOLLOHOSP": "Apollo Hospitals Enterprise",
    "ASHOKLEY": "Ashok Leyland", "ASIANPAINT": "Asian Paints", "ASTRAMICRO": "Astra Microwave Products",
    "AUBANK": "AU Small Finance Bank", "AUROPHARMA": "Aurobindo Pharma", "AXISBANK": "Axis Bank", "BAJAJ-AUTO": "Bajaj Auto",
    "BAJAJFINSV": "Bajaj Finserv", "BAJFINANCE": "Bajaj Finance", "BALKRISIND": "Balkrishna Industries",
    "BANDHANBNK": "Bandhan Bank", "BANKBARODA": "Bank of Baroda", "BANKINDIA": "Bank of India", "BATAINDIA": "Bata India",
    "BDL": "Bharat Dynamics", "BEL": "Bharat Electronics", "BEML": "BEML", "BHARATFORG": "Bharat Forge",
    "BHARTIARTL": "Bharti Airtel", "BIOCON": "Biocon", "BLUESTARCO": "Blue Star", "BOSCHLTD": "Bosch",
    "BPCL": "Bharat Petroleum Corporation", "BRIGADE": "Brigade Enterprises", "BRITANNIA": "Britannia Industries",
    "BSE": "BSE", "CAMS": "Computer Age Management Services", "CANBK": "Canara Bank",
    "CDSL": "Central Depository Services (India)", "CENTRALBK": "Central Bank of India", "CHALET": "Chalet Hotels",
    "CHOLAFIN": "Cholamandalam Investment and Finance Company", "CIPLA": "Cipla", "COALINDIA": "Coal India",
    "COCHINSHIP": "Cochin Shipyard", "COFORGE": "Coforge", "COLPAL": "Colgate Palmolive (India)",
    "CROMPTON": "Crompton Greaves Consumer Electricals", "CUB": "City Union Bank", "DABUR": "Dabur India",
    "DATAPATTNS": "Data Patterns (India)", "DBCORP": "D B Corp", "DEEPAKNTR": "Deepak Nitrite",
    "DEVYANI": "Devyani International", "DIVISLAB": "Divi's Laboratories", "DIXON": "Dixon Technologies (India)",
    "DLF": "DLF", "DRREDDY": "Dr. Reddy's Laboratories", "EICHERMOT": "Eicher Motors", "EIHOTEL": "EIH",
    "EMAMILTD": "Emami", "ETERNAL": "Eternal", "EXIDEIND": "Exide Industries", "FEDERALBNK": "The Federal Bank",
    "FORTIS": "Fortis Healthcare", "GAIL": "GAIL (India)", "GLENMARK": "Glenmark Pharmaceuticals",
    "GODREJCP": "Godrej Consumer Products", "GODREJPROP": "Godrej Properties", "GRASIM": "Grasim Industries",
    "GRSE": "Garden Reach Shipbuilders & Engineers", "GUJGASLTD": "Gujarat Gas", "HAL": "Hindustan Aeronautics",
    "HAVELLS": "Havells India", "HCLTECH": "HCL Technologies", "HDFCAMC": "HDFC Asset Management Company",
    "HDFCBANK": "HDFC Bank", "HDFCLIFE": "HDFC Life Insurance Company", "HEROMOTOCO": "Hero MotoCorp",
    "HINDALCO": "Hindalco Industries", "HINDCOPPER": "Hindustan Copper", "HINDPETRO": "Hindustan Petroleum Corporation",
    "HINDUNILVR": "Hindustan Unilever", "HINDZINC": "Hindustan Zinc", "ICICIBANK": "ICICI Bank",
    "ICICIGI": "ICICI Lombard General Insurance Company", "IDFCFIRSTB": "IDFC First Bank", "IEX": "Indian Energy Exchange",
    "IGL": "Indraprastha Gas", "INDHOTEL": "The Indian Hotels Company", "INDIANB": "Indian Bank",
    "INDIGO": "InterGlobe Aviation", "INDUSINDBK": "IndusInd Bank", "INFY": "Infosys", "IOB": "Indian Overseas Bank",
    "IOC": "Indian Oil Corporation", "IPCALAB": "IPCA Laboratories",
    "IRCTC": "Indian Railway Catering and Tourism Corporation", "ITC": "ITC", "JINDALSTEL": "Jindal Steel & Power",
    "JIOFIN": "Jio Financial Services", "JSL": "Jindal Stainless", "JSWENERGY": "JSW Energy", "JSWSTEEL": "JSW Steel",
    "JUBLFOOD": "Jubilant Foodworks", "KALYANKJIL": "Kalyan Jewellers India", "KFINTECH": "KFin Technologies",
    "KOTAKBANK": "Kotak Mahindra Bank", "LAURUSLABS": "Laurus Labs", "LEMONTREE": "Lemon Tree Hotels",
    "LODHA": "Lodha Developers", "LT": "Larsen & Toubro", "LUPIN": "Lupin", "M&M": "Mahindra & Mahindra",
    "MAHABANK": "Bank of Maharashtra", "MANKIND": "Mankind Pharma", "MARICO": "Marico", "MARUTI": "Maruti Suzuki India",
    "MAXHEALTH": "Max Healthcare Institute", "MAZDOCK": "Mazagon Dock Shipbuilders",
    "MCX": "Multi Commodity Exchange of India", "MGL": "Mahanagar Gas", "MOTHERSON": "Samvardhana Motherson International",
    "MOTILALOFS": "Motilal Oswal Financial Services", "MPHASIS": "Mphasis", "MRF": "MRF",
    "NATIONALUM": "National Aluminium Company", "NAVINFLUOR": "Navin Fluorine International",
    "NAZARA": "Nazara Technologies", "NESTLEIND": "Nestle India", "NETWORK18": "Network18 Media & Investments",
    "NHPC": "NHPC", "NLCINDIA": "NLC India", "NMDC": "NMDC", "NTPC": "NTPC", "NUVAMA": "Nuvama Wealth Management",
    "OBEROIRLTY": "Oberoi Realty", "OFSS": "Oracle Financial Services Software", "OIL": "Oil India",
    "ONGC": "Oil & Natural Gas Corporation", "PATANJALI": "Patanjali Foods", "PERSISTENT": "Persistent Systems",
    "PETRONET": "Petronet LNG", "PFC": "Power Finance Corporation", "PHOENIXLTD": "The Phoenix Mills",
    "PIDILITIND": "Pidilite Industries", "PIIND": "PI Industries", "PNB": "Punjab National Bank",
    "POWERGRID": "Power Grid Corporation of India", "PRESTIGE": "Prestige Estates Projects", "PSB": "Punjab & Sind Bank",
    "PVRINOX": "PVR INOX", "RADICO": "Radico Khaitan", "RBLBANK": "RBL Bank", "RECLTD": "REC",
    "RELIANCE": "Reliance Industries", "SAIL": "Steel Authority of India", "SAREGAMA": "Saregama India",
    "SBILIFE": "SBI Life Insurance Company", "SBIN": "State Bank of India", "SHREECEM": "Shree Cement",
    "SHRIRAMFIN": "Shriram Finance", "SIEMENS": "Siemens", "SJVN": "SJVN", "SOBHA": "Sobha",
    "SOLARINDS": "Solar Industries India", "SRF": "SRF", "SUNPHARMA": "Sun Pharmaceutical Industries",
    "SUNTV": "Sun TV Network", "TATACHEM": "Tata Chemicals", "TATACONSUM": "Tata Consumer Products",
    "TATAPOWER": "Tata Power Company", "TATASTEEL": "Tata Steel", "TCS": "Tata Consultancy Services",
    "TECHM": "Tech Mahindra", "TIINDIA": "Tube Investments of India", "TIPSMUSIC": "Tips Music", "TITAN": "Titan Company",
    "TMPV": "Tata Motors Passenger Vehicles", "TORNTPHARM": "Torrent Pharmaceuticals", "TRENT": "Trent",
    "TVSMOTOR": "TVS Motor Company", "UCOBANK": "UCO Bank", "ULTRACEMCO": "UltraTech Cement",
    "UNIONBANK": "Union Bank of India", "UNITDSPR": "United Spirits", "UPL": "UPL", "VBL": "Varun Beverages",
    "VEDL": "Vedanta", "VOLTAS": "Voltas", "WELCORP": "Welspun Corp", "WESTLIFE": "Westlife Foodworld",
    "WHIRLPOOL": "Whirlpool of India", "WIPRO": "Wipro", "ZEEL": "Zee Entertainment Enterprises",
    "ZYDUSLIFE": "Zydus Lifesciences",
}


def name_of(symbol: str) -> str:
    """A listed company's name; a symbol not in the table keeps the old title-cased stand-in."""
    return NAMES.get(symbol, symbol.title())
