/* Plain-English explanations behind every (i) button. Keep each to two or three short sentences. */
export const HELP = {
  notebook: "A notebook holds one trading idea. You write the question you want answered, set the rules, then run experiments until you know whether the idea really works.",
  question: "The question this notebook is trying to answer. Click it to rewrite it in your own words.",
  market: "What the rules trade: a stock, index or coin, and its market. Prices, trading hours, currency and costs all follow the market.",
  rules: "The exact rules the computer follows, checked once each time a candle closes. Click any highlighted word to change it: the indicator, its length, the condition, or a number.",
  crosses: "\"Crosses above\" is true only on the one candle where the line moves from below to above. \"Is above\" is true on every candle while it stays above, so it trades more often.",
  stop: "A stop loss sells automatically if the price falls this far below your buy price. It limits how much one bad trade can lose. 0 turns it off.",
  target: "A target sells automatically once the price rises this far above your buy price, locking in the gain. 0 turns it off.",
  risk: "How much of your capital you'd lose if the stop loss hits. It sets how many shares to buy: quantity = risk amount ÷ distance to the stop. Most traders keep this at 1% or less.",
  capital: "Pretend money the test starts with. Use roughly what you'd really trade with, so the numbers mean something.",
  candles: "A candle is one block of time on the chart. Daily candles suit trades that last days or weeks; shorter candles mean more trades, more noise and more costs.",
  period: "How far back to test. Longer periods include more market conditions (rising, falling and sideways), so the verdict is more reliable.",
  runExperiment: "Runs your rules on past prices with realistic costs, then runs four honesty checks to judge whether the result is a real edge or luck. Each run uses one experiment from your monthly allowance.",
  experiments: "Every test you run is saved here with its verdict, so you can compare versions and see which change helped.",
  labNotes: "Your own notes: what you noticed, what you want to try next. Only you can see them.",
  nextSteps: "Ideas for your next experiment, based on the last verdict.",
  paper: "Paper trading runs your rules on live prices with fake money, so you can watch how they behave in real time without risking anything. No real orders are placed.",
  verdict: "The one-line answer: is this a real edge or luck? It comes from the four checks below, all measured after trading costs.",
  strength: "How many of the four honesty checks passed. Skipped checks (for example, too few trades to reshuffle) aren't counted.",
  unseen: "We split the test period: the first 70% is where the rules were tuned, the last 30% is data they've never seen. A real edge keeps making money on the unseen part.",
  nearby: "We nudge your indicator lengths up and down (for example EMA 16, 18, 22 and 24 instead of 20) and test each version. If only your exact numbers make money, it's probably a lucky fit. Blue squares made money; orange lost.",
  shuffle: "We reshuffle the order of your trades 1,000 times. The same trades in a worse order can fall much deeper. This shows the drawdown you should be ready for.",
  sample: "Under 15 trades, a couple of lucky trades can decide the whole result. 30 or more trades is a fair sample.",
  equity: "How the test account's value moved over time. The dashed line is what simply buying and holding would have done. The shaded part is the unseen data.",
  keep: "Profit after every cost of trading in this market: brokerage, taxes like STT and stamp duty, exchange fees and GST, plus an estimate of tax on the gains.",
  priceChart: "The price over the test, with your indicators drawn on top. Blue triangles mark buys; orange ones mark sells.",
  totalReturn: "Profit or loss on your starting capital over the whole test, after costs.",
  buyHold: "What you'd have made by simply buying at the start and holding to the end. A strategy should beat this to be worth the effort.",
  worstFall: "The biggest fall from a high point to a low point in your account during the test (maximum drawdown).",
  winRate: "The share of closed trades that made money. A low win rate is fine if the winners are much bigger than the losers.",
  profitFactor: "Money made on winning trades for every ₹1 lost on losing trades. Above 1 means the winners outweigh the losers.",
  sharpe: "Return compared with how bumpy the ride was. Above 1 is good; below 0.5 means the gains came with a lot of swings.",
  avgTrade: "The average profit or loss per closed trade, after costs.",
  trades: "Every trade the rules made, newest first. \"Why it sold\" shows whether the stop loss, the target or your sell rule closed it.",
  markets: "Pick where to test your rules. Live markets have real prices built in. For anything else, upload your own price history as a CSV.",
  csv: "A spreadsheet of candles, one row per candle, with columns for date, open, high, low, close and (optionally) volume. Most charting sites and brokers can export this.",
  quantities: "Whole units for shares and F&O lots. Fractions for coins and currencies, where you can buy 0.01 of a unit.",
  equityLive: "The fake account's value after each closed candle.",
  unrealised: "Profit or loss on the position you're still holding, at the latest price.",
  realised: "Profit or loss from trades that have already closed.",
  cash: "Fake money not currently in a trade.",
  feed: "Whether live prices are arriving. Indian markets trade 9:15 am to 3:30 pm IST on weekdays; crypto trades around the clock.",
  connection: "Checks your sign-in, the StratLab server, each market's live data and the AI builder. Run it if something isn't loading.",
  alerts: "Get a Telegram message or email whenever a paper trading session buys or sells.",
  experimentsQuota: "Each experiment is one backtest plus its honesty checks. Your plan includes a number of them each month.",
  short: "Selling short means selling first and buying back later, so you profit when the price falls and lose when it rises. The test assumes you can borrow the shares or use futures; Indian cash stocks can only be shorted within the day.",
  trail: "A stop that follows the price. For a buy it stays a set % below the highest price since you bought, and only ever moves up, so it locks in gains while letting winners run.",
  maxBars: "Closes a trade after a set number of candles if nothing else has, so money isn't tied up in trades that go nowhere.",
  basket: "Runs these exact rules, over the same period and with the same costs, on about 10 well-known instruments from the same market. If most of them make money too, the idea is more likely a real pattern; if only your pick does, it was probably that chart.",
  researchPulse: "Live levels of the main indices, how far each is from its 52-week high, and an AI read of today's mood built only from those numbers and the latest headlines.",
  researchThemes: "Type a sector or trend and the AI maps the companies involved, where the margin sits, and ranks the ones worth a closer look.",
  research52: "Where today's price sits between the lowest and highest price of the past year. Near the top means it has been strong lately; near the bottom, weak.",
  researchMargins: "How much of each sale is left after each layer of costs: making the product, running the business, then tax and interest.",
  researchMetrics: "The main numbers, grouped. The dot on each line shows where this company sits in a typical range for its industry: blue is strong, orange is weak. The two ticks mark the edges of normal.",
  researchEarnings: "Each quarter's earnings per share against what analysts expected. Blue bars beat the estimate, orange bars missed it.",
  researchHolding: "Who owns the shares: the founders or promoters, foreign funds (FIIs), Indian funds (DIIs) and the public. Promoters selling or funds piling in can be worth watching.",
};
