/* The kit: one component per job. Read stratlab/frontend/DESIGN.md before adding to it. */
export { PageHeader } from "./PageHeader";
export { Card, CardHead } from "./Card";
export { Stat, StatRow, Delta } from "./Stat";
export { Badge } from "./Badge";
export { Seg, type Choice } from "./Seg";
export { ChipBar, type CustomUnit } from "./ChipBar";
export { FormGrid, Field, FieldGroup, FormActions, Select } from "./Form";
export { StockPicker } from "./StockPicker";
export { Suggest, type SuggestItem } from "./Suggest";
export { TilePicker, type Tile, type TileGroup } from "./TilePicker";
export { DataTable, type Column } from "./DataTable";
export { Notice, PlanNote } from "./Notice";
export { ConfirmDialog } from "./ConfirmDialog";
export { BarList, Meter } from "./BarList";
export { Disclosure } from "./Disclosure";
export { UploadButton } from "./UploadButton";
export { ChipSet, CheckField } from "./Choices";
export { EmptyState, ErrorState, Skeleton, type StateAction } from "./States";
export { ChartFrame } from "./ChartFrame";
export { ResultBlock } from "./ResultBlock";
export { LinkCard } from "./LinkCard";
export { Spark } from "./Spark";
export { Breadcrumb, type Crumb, type Sibling } from "./Breadcrumb";
