import type { Plugin } from "vite";
export function homeJsonLd(): string;
export function faqJsonLd(): string;
export function bootBody(page: { heading: string; summary: string[]; faq?: boolean }): string;
export function pageHtml(template: string, page: { title: string; description: string; canonical: string | null; index: boolean; jsonld?: string;
  heading?: string; summary?: string[]; faq?: boolean }): string;
export function pageFiles(template: string): [string, string][];
export function libraryFiles(template: string, entries?: Record<string, unknown>): [string, string][];
export function apiBase(env?: Record<string, string | undefined>, vercel?: unknown): string | null;
export function libraryEntries(env?: Record<string, string | undefined>, get?: typeof fetch): Promise<Record<string, unknown>>;
export function seoPages(): Plugin;
